kind: ConfigMap
apiVersion: v1
metadata:
  name: vod-ms-journey-upgrade
data:
  log.level: debug
  sentry.dsn: "https://e7711b7ed2a34b9baff852b63240f023@o185340.ingest.sentry.io/5746935"
  sentry.maxBreadcrumbs: "99"
  sentry.httpProxy: "http://vod-ms-egress-proxy.cluster-services:3128"